[project]
name = "ytvidauto"
version = "0.1.0"
description = "High-performance automated video generation API utilizing FastAPI and raw FFmpeg for synchronized slideshow creation."
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "fastapi",
    "pydantic",
    "httpx",
    "python-multipart",
    "workers-py",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "uvicorn",
]
